// Auto-generated by babel-plugin-minimact
// Source: CSharpFileExample.tsx

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Minimact;
using Minimact.VDom;

namespace MyApp.Components
{
    [Component]
    public partial class CSharpFileExample : MinimactComponent
    {
        [State]
        private List<Product> products = new List<Product>();

        [State]
        private bool loading = false;

        [ServerTask]
        public async Task<object> fetchProducts()
        {
            var response = await HttpClient.GetAsync("/api/products");
            return await response.Content.ReadFromJsonAsync<object>();
        }

        protected override VNode Render()
        {
            return new VElement("div", "1", new Dictionary<string, string> { ["class"] = "product-list" }, new VNode[]
            {
                (loading)
                    ? new VElement("span", "1.1", new Dictionary<string, string>(), "Loading...")
                    : new VNull("1.1"),
                new VElement("ul", "1.2", new Dictionary<string, string>(),
                    products.Select(p => new VElement("li", "1.2.1", new Dictionary<string, string>
                    {
                        ["key"] = $"{p.id}"
                    }, new VText($"{p.name}: ${p.price.ToString("F2")}", "1.2.1.1"))).ToArray())
            });
        }
    }
}

// csharpFile.cjs adds:
// 1. File header comment with source file
// 2. Required using statements based on features used
// 3. Namespace wrapper (from config or source path)
// 4. All component classes from the file
