using Minimact;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

[Component]
public partial class ProcessComponentExample : MinimactComponent
{
    // Top-level constants (detected in Program.enter)
    private static readonly int DEFAULT_PAGE_SIZE = 10;

    // Props (extracted from function parameters)
    [Prop]
    public User initialUser { get; set; }

    // State (extracted by extractHook → extractUseState)
    [State]
    private User user;

    [State]
    private List<string> items = new List<string>();

    // Refs (extracted by extractHook → extractUseRef)
    [Ref]
    private ElementRef inputRef = null;

    // Constructor initializes state from props
    public ProcessComponentExample()
    {
        user = initialUser;
    }

    // Server task (extracted by extractHook → extractUseServerTask)
    [ServerTask]
    public async Task<object> fetchItems(double userId)
    {
        var response = await HttpClient.GetAsync($"/api/users/{userId}/items");
        return await response.Content.ReadFromJsonAsync<object>();
    }

    // Top-level helper functions (detected in Program.enter, referenced by component)
    private string formatDate(DateTime date)
    {
        return date.ToString("yyyy-MM-dd");
    }

    // Event handlers (extracted during JSX processing)
    private void Handle0()
    {
        items = new List<string>();
        SetState(nameof(items), items);
    }

    // Render method (generated by renderBody.cjs)
    protected override VNode Render()
    {
        // Local variables (extracted by extractLocalVariables)
        var itemCount = items.Count;
        var today = formatDate(DateTime.Now);

        return new VElement("div", "1", new Dictionary<string, string> { ["class"] = "user-panel" }, new VNode[]
        {
            new VElement("h1", "1.1", new Dictionary<string, string>(), new VText($"Welcome, {user.name}", "1.1.1")),
            new VElement("p", "1.2", new Dictionary<string, string>(), new VText($"Email: {user.email}", "1.2.1")),
            new VElement("p", "1.3", new Dictionary<string, string>(), new VText($"Items: {itemCount} (as of {today})", "1.3.1")),
            new VElement("input", "1.4", new Dictionary<string, string> { ["ref"] = "inputRef", ["placeholder"] = "Search..." }),
            new VElement("ul", "1.5", new Dictionary<string, string>(),
                items.Select(item => new VElement("li", "1.5.1", new Dictionary<string, string> { ["key"] = $"{item}" },
                    new VText($"{item}", "1.5.1.1"))).ToArray()),
            new VElement("button", "1.6", new Dictionary<string, string> { ["onclick"] = "Handle0" }, "Clear")
        });
    }
}

// processComponent.cjs orchestrates:
// 1. getComponentName() - extracts function name
// 2. isCustomHook() - checks if it's a hook (skips to processCustomHook)
// 3. analyzeImportedHooks() - finds imported hook metadata
// 4. Extract props from function parameters
// 5. Track external imports for client-computed detection
// 6. Traverse body:
//    - extractHook() for each CallExpression
//    - extractLocalVariables() for VariableDeclarations
//    - Collect helper FunctionDeclarations
//    - Find ReturnStatement for renderBody
// 7. inferPropTypes() from usage patterns
// 8. assignPathsToJSX() for hot reload paths
// 9. Extract all template types (text, loop, structural, conditional, expression)
// 10. Detect top-level function/constant references
// 11. Store component for C# generation
