// Generated by typescriptToRust.cjs
// Source: TypeScriptToRustExample.tsx

use rayon::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Serialize)]
pub struct ComputeStatsResult {
    pub sum: f64,
    pub mean: f64,
    pub variance: f64,
    pub std_dev: f64,
}

/// Numeric computation with parallel iteration (Rayon)
#[no_mangle]
pub extern "C" fn compute_stats(numbers: Vec<f64>) -> ComputeStatsResult {
    // reduce((a, b) => a + b, 0) → .par_iter().sum()
    let sum: f64 = numbers.par_iter().sum();

    // numbers.length → numbers.len()
    let mean = sum / numbers.len() as f64;

    // .map(n => (n - mean) ** 2) → .par_iter().map(|n| (n - mean).powi(2))
    let squared_diffs: Vec<f64> = numbers
        .par_iter()
        .map(|n| (n - mean).powi(2))
        .collect();

    let variance: f64 = squared_diffs.par_iter().sum::<f64>() / numbers.len() as f64;

    // Math.sqrt() → .sqrt()
    let std_dev = variance.sqrt();

    ComputeStatsResult { sum, mean, variance, std_dev }
}

/// String processing
#[no_mangle]
pub extern "C" fn process_text(text: String) -> String {
    // .split(' ') → .split(' ')
    let words: Vec<&str> = text.split(' ').collect();

    // .filter(w => w.length > 3) → .filter(|w| w.len() > 3)
    let filtered: Vec<&str> = words
        .into_iter()
        .filter(|w| w.len() > 3)
        .collect();

    // .map(w => w.toUpperCase()) → .map(|w| w.to_uppercase())
    let upper: Vec<String> = filtered
        .into_iter()
        .map(|w| w.to_uppercase())
        .collect();

    // .join(' ') → .join(" ")
    upper.join(" ")
}

// typescriptToRust.cjs transpiles:
// - number[] → Vec<f64>
// - string[] → Vec<String>
// - string → String
// - .length → .len()
// - .push() → .push()
// - .map() → .iter().map().collect()
// - .filter() → .iter().filter().collect()
// - .reduce() → .iter().fold() or .sum()
// - Math.sqrt/abs/floor/ceil → .sqrt()/.abs()/.floor()/.ceil()
// - ** (exponent) → .powi() or .powf()
// - Template literals → format!()
// - { parallel: true } → uses rayon::par_iter()
