using System;
using System.IO;
using System.Text.Json;
using Minimact.Transpiler.CodeGen.Nodes;
using Minimact.Transpiler.CodeGen.Visitors;

namespace Minimact.Transpiler.CodeGen;

/// <summary>
/// Main transpiler class that orchestrates JSON → C# code generation
/// </summary>
public class Transpiler
{
    private readonly JsonSerializerOptions _jsonOptions;

    public Transpiler()
    {
        _jsonOptions = new JsonSerializerOptions
        {
            PropertyNameCaseInsensitive = true,
            ReadCommentHandling = JsonCommentHandling.Skip,
            AllowTrailingCommas = true
        };
    }

    /// <summary>
    /// Transpile a JSON file to C# code
    /// </summary>
    /// <param name="jsonFilePath">Path to JSON file generated by Babel plugin</param>
    /// <param name="outputDir">Output directory for generated C# files</param>
    public void TranspileFile(string jsonFilePath, string outputDir)
    {
        if (!File.Exists(jsonFilePath))
        {
            throw new FileNotFoundException($"JSON file not found: {jsonFilePath}");
        }

        Console.WriteLine($"[Minimact Transpiler] Reading: {jsonFilePath}");

        // Read and deserialize JSON
        var jsonContent = File.ReadAllText(jsonFilePath);
        var component = JsonSerializer.Deserialize<ComponentNode>(jsonContent, _jsonOptions);

        if (component == null)
        {
            throw new InvalidOperationException($"Failed to deserialize component from {jsonFilePath}");
        }

        Console.WriteLine($"[Minimact Transpiler] Component: {component.ComponentName}");

        // Generate C# code using visitor pattern
        var codeGenerator = new CSharpCodeGenerator();
        component.Accept(codeGenerator);
        var generatedCode = codeGenerator.GetOutput();

        // Write to output file
        if (!Directory.Exists(outputDir))
        {
            Directory.CreateDirectory(outputDir);
        }

        var outputFilePath = Path.Combine(outputDir, $"{component.ComponentName}.Generated.cs");
        File.WriteAllText(outputFilePath, generatedCode);

        Console.WriteLine($"[Minimact Transpiler] ✅ Generated: {outputFilePath}");
    }

    /// <summary>
    /// Transpile all JSON files in a directory
    /// </summary>
    /// <param name="jsonDir">Directory containing JSON files</param>
    /// <param name="outputDir">Output directory for generated C# files</param>
    public void TranspileDirectory(string jsonDir, string outputDir)
    {
        if (!Directory.Exists(jsonDir))
        {
            throw new DirectoryNotFoundException($"JSON directory not found: {jsonDir}");
        }

        var jsonFiles = Directory.GetFiles(jsonDir, "*.json");

        if (jsonFiles.Length == 0)
        {
            Console.WriteLine($"[Minimact Transpiler] No JSON files found in {jsonDir}");
            return;
        }

        Console.WriteLine($"[Minimact Transpiler] Found {jsonFiles.Length} JSON file(s)");
        Console.WriteLine();

        foreach (var jsonFile in jsonFiles)
        {
            try
            {
                TranspileFile(jsonFile, outputDir);
            }
            catch (Exception ex)
            {
                Console.Error.WriteLine($"[Minimact Transpiler] Error processing {jsonFile}: {ex.Message}");
            }
        }

        Console.WriteLine();
        Console.WriteLine($"[Minimact Transpiler] ✅ Transpilation complete!");
    }
}
