namespace Minimact.AspNetCore.Core;

/// <summary>
/// Binds a state variable to timeline control with optional interpolation.
/// Generated by Babel plugin from useTimelineState() calls in JSX.
/// Enables server to understand which states are animated by the timeline.
/// </summary>
/// <remarks>
/// This attribute is automatically generated at compile-time by the Babel plugin.
/// It declares how state variables respond to timeline playback.
///
/// Example:
/// [TimelineStateBinding("count", Interpolate = true)]  // Smooth number interpolation
/// [TimelineStateBinding("color", Interpolate = false)] // Snap to next value
///
/// Interpolation behavior:
/// - true: Smooth interpolation between keyframes (for numbers)
/// - false: Snap to next value at 50% progress (for strings, booleans)
///
/// This metadata enables:
/// - Server to track which states are timeline-controlled
/// - Client to apply correct interpolation logic
/// - Rust predictor to generate accurate patches
/// </remarks>
[AttributeUsage(AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
public class TimelineStateBindingAttribute : Attribute
{
    /// <summary>
    /// State key that is bound to the timeline (e.g., "count", "opacity")
    /// </summary>
    public string StateKey { get; }

    /// <summary>
    /// Whether to interpolate values between keyframes
    /// </summary>
    public bool Interpolate { get; set; } = false;

    /// <summary>
    /// Creates a new timeline state binding attribute
    /// </summary>
    /// <param name="stateKey">State variable name</param>
    public TimelineStateBindingAttribute(string stateKey)
    {
        StateKey = stateKey;
    }
}
