namespace Minimact.AspNetCore.Core;

/// <summary>
/// Defines a keyframe at a specific time with a state value.
/// Generated by Babel plugin from timeline.keyframes() calls in JSX.
/// Enables server to reconstruct timeline state at any point in time.
/// </summary>
/// <remarks>
/// This attribute is automatically generated at compile-time by the Babel plugin.
/// Multiple keyframes combine to form the complete timeline.
///
/// Example:
/// [TimelineKeyframe(0, "count", 0)]
/// [TimelineKeyframe(2500, "count", 50)]
/// [TimelineKeyframe(5000, "count", 100, Label = "end")]
///
/// The server uses these keyframes to:
/// - Pre-compute VNode states at each keyframe
/// - Generate patches between keyframes
/// - Schedule patch delivery via SignalR
/// - Enable client interpolation for smooth animations
/// </remarks>
[AttributeUsage(AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
public class TimelineKeyframeAttribute : Attribute
{
    /// <summary>
    /// Time in milliseconds when this state value should be active
    /// </summary>
    public int Time { get; }

    /// <summary>
    /// State key this keyframe affects (e.g., "count", "color")
    /// </summary>
    public string StateKey { get; }

    /// <summary>
    /// Value to set at this time (number, string, boolean, or null)
    /// </summary>
    public object Value { get; }

    /// <summary>
    /// Optional label for seeking (e.g., "intro", "main", "outro")
    /// </summary>
    public string? Label { get; set; }

    /// <summary>
    /// Optional easing function override for this keyframe
    /// </summary>
    public string? Easing { get; set; }

    /// <summary>
    /// Creates a new timeline keyframe attribute
    /// </summary>
    /// <param name="time">Time in milliseconds</param>
    /// <param name="stateKey">State variable name</param>
    /// <param name="value">Value at this time</param>
    public TimelineKeyframeAttribute(int time, string stateKey, object value)
    {
        Time = time;
        StateKey = stateKey;
        Value = value;
    }
}
