namespace Minimact.AspNetCore.Core;

/// <summary>
/// Defines a timeline for time-based state orchestration.
/// Generated by Babel plugin from useTimeline() calls in JSX.
/// Enables server-side pre-computation of patches for entire timeline.
/// </summary>
/// <remarks>
/// This attribute is automatically generated at compile-time by the Babel plugin.
/// It contains timeline configuration extracted from TSX.
///
/// Example:
/// [Timeline("AnimatedCounter_Timeline", 5000, Repeat = true, Easing = "ease-in-out")]
///
/// The timeline metadata enables:
/// - Server-side patch pre-computation for entire duration
/// - SignalR delivery of patches at scheduled times
/// - Zero-latency predictive rendering with 100% coverage
/// - Perfect synchronization with grains and component state
/// </remarks>
[AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
public class TimelineAttribute : Attribute
{
    /// <summary>
    /// Unique identifier for this timeline (e.g., "AnimatedCounter_Timeline")
    /// </summary>
    public string TimelineId { get; }

    /// <summary>
    /// Total duration of the timeline in milliseconds
    /// </summary>
    public int Duration { get; }

    /// <summary>
    /// Whether the timeline should loop continuously
    /// </summary>
    public bool Repeat { get; set; } = false;

    /// <summary>
    /// Number of times to repeat (-1 for infinite when Repeat is true)
    /// </summary>
    public int RepeatCount { get; set; } = -1;

    /// <summary>
    /// Global easing function: linear, ease-in, ease-out, ease-in-out
    /// </summary>
    public string Easing { get; set; } = "linear";

    /// <summary>
    /// Creates a new timeline attribute
    /// </summary>
    /// <param name="timelineId">Unique timeline identifier</param>
    /// <param name="duration">Total duration in milliseconds</param>
    public TimelineAttribute(string timelineId, int duration)
    {
        TimelineId = timelineId;
        Duration = duration;
    }
}
