// <auto-generated />
using System;
using Mactic.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace Mactic.Api.Migrations
{
    [DbContext(typeof(MacticDbContext))]
    partial class MacticDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mactic.Api.Models.Community.ActivityEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeveloperId")
                        .HasColumnType("uuid");

                    b.Property<int>("EngagementScore")
                        .HasColumnType("integer");

                    b.Property<string>("EventData")
                        .HasColumnType("jsonb");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DeveloperId");

                    b.HasIndex("EventType");

                    b.HasIndex("ProjectId");

                    b.ToTable("ActivityEvents");
                });

            modelBuilder.Entity("Mactic.Api.Models.Community.Badge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("DeveloperId")
                        .HasColumnType("uuid");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RequirementThreshold")
                        .HasColumnType("integer");

                    b.Property<string>("RequirementType")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Badges");
                });

            modelBuilder.Entity("Mactic.Api.Models.Community.Developer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GitHubUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsOpenToCollaboration")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOpenToConsulting")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastActiveAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<int>("Reputation")
                        .HasColumnType("integer");

                    b.Property<bool>("ShowEmailPublicly")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowLocationPublicly")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<string[]>("Skills")
                        .HasColumnType("jsonb");

                    b.Property<string>("TwitterHandle")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("LastActiveAt");

                    b.HasIndex("Reputation");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Developers");
                });

            modelBuilder.Entity("Mactic.Api.Models.Community.DeveloperBadge", b =>
                {
                    b.Property<Guid>("DeveloperId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BadgeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AwardedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DeveloperId", "BadgeId");

                    b.HasIndex("BadgeId");

                    b.ToTable("DeveloperBadges");
                });

            modelBuilder.Entity("Mactic.Api.Models.Community.DeveloperConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FollowerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FollowerId1")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FollowingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FollowingId1")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FollowerId1");

                    b.HasIndex("FollowingId");

                    b.HasIndex("FollowingId1");

                    b.HasIndex("FollowerId", "FollowingId")
                        .IsUnique();

                    b.ToTable("DeveloperConnections");
                });

            modelBuilder.Entity("Mactic.Api.Models.Community.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AverageRating")
                        .HasColumnType("double precision");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CloneCount")
                        .HasColumnType("integer");

                    b.Property<string>("ContentSnapshot")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("DeveloperId")
                        .HasColumnType("uuid");

                    b.Property<string>("DocsUrl")
                        .HasColumnType("text");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1536)");

                    b.Property<int>("ForkCount")
                        .HasColumnType("integer");

                    b.Property<string>("GitHubUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTrending")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastDeployedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer");

                    b.Property<string>("SemanticallyRelatedTopics")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DeveloperId");

                    b.HasIndex("IsFeatured");

                    b.HasIndex("IsTrending");

                    b.HasIndex("LastUpdatedAt");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Mactic.Api.Models.Community.ProjectDependency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DependencyProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("DependencyType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DependentProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DependencyProjectId");

                    b.HasIndex("DependentProjectId", "DependencyProjectId")
                        .IsUnique();

                    b.ToTable("ProjectDependencies");
                });

            modelBuilder.Entity("Mactic.Api.Models.Community.ProjectUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeveloperId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FirstUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActivelyUsing")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperId");

                    b.HasIndex("ProjectId", "DeveloperId")
                        .IsUnique();

                    b.ToTable("ProjectUsages");
                });

            modelBuilder.Entity("Mactic.Api.Models.Community.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeveloperId")
                        .HasColumnType("uuid");

                    b.Property<int>("HelpfulCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DeveloperId");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("ProjectId", "ReviewerId")
                        .IsUnique();

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Mactic.Api.Models.Community.ActivityEvent", b =>
                {
                    b.HasOne("Mactic.Api.Models.Community.Developer", "Developer")
                        .WithMany()
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Mactic.Api.Models.Community.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Developer");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Mactic.Api.Models.Community.Badge", b =>
                {
                    b.HasOne("Mactic.Api.Models.Community.Developer", null)
                        .WithMany("Badges")
                        .HasForeignKey("DeveloperId");
                });

            modelBuilder.Entity("Mactic.Api.Models.Community.DeveloperBadge", b =>
                {
                    b.HasOne("Mactic.Api.Models.Community.Badge", "Badge")
                        .WithMany("DeveloperBadges")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mactic.Api.Models.Community.Developer", "Developer")
                        .WithMany()
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("Developer");
                });

            modelBuilder.Entity("Mactic.Api.Models.Community.DeveloperConnection", b =>
                {
                    b.HasOne("Mactic.Api.Models.Community.Developer", null)
                        .WithMany()
                        .HasForeignKey("FollowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mactic.Api.Models.Community.Developer", "Follower")
                        .WithMany()
                        .HasForeignKey("FollowerId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mactic.Api.Models.Community.Developer", null)
                        .WithMany("Connections")
                        .HasForeignKey("FollowingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mactic.Api.Models.Community.Developer", "Following")
                        .WithMany()
                        .HasForeignKey("FollowingId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Follower");

                    b.Navigation("Following");
                });

            modelBuilder.Entity("Mactic.Api.Models.Community.Project", b =>
                {
                    b.HasOne("Mactic.Api.Models.Community.Developer", "Developer")
                        .WithMany("Projects")
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Developer");
                });

            modelBuilder.Entity("Mactic.Api.Models.Community.ProjectDependency", b =>
                {
                    b.HasOne("Mactic.Api.Models.Community.Project", "DependencyProject")
                        .WithMany("DependentProjects")
                        .HasForeignKey("DependencyProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mactic.Api.Models.Community.Project", "DependentProject")
                        .WithMany("Dependencies")
                        .HasForeignKey("DependentProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DependencyProject");

                    b.Navigation("DependentProject");
                });

            modelBuilder.Entity("Mactic.Api.Models.Community.ProjectUsage", b =>
                {
                    b.HasOne("Mactic.Api.Models.Community.Developer", "Developer")
                        .WithMany()
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mactic.Api.Models.Community.Project", "Project")
                        .WithMany("Usages")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Developer");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Mactic.Api.Models.Community.Review", b =>
                {
                    b.HasOne("Mactic.Api.Models.Community.Developer", null)
                        .WithMany("ReviewsReceived")
                        .HasForeignKey("DeveloperId");

                    b.HasOne("Mactic.Api.Models.Community.Project", "Project")
                        .WithMany("Reviews")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mactic.Api.Models.Community.Developer", "Reviewer")
                        .WithMany("ReviewsGiven")
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("Mactic.Api.Models.Community.Badge", b =>
                {
                    b.Navigation("DeveloperBadges");
                });

            modelBuilder.Entity("Mactic.Api.Models.Community.Developer", b =>
                {
                    b.Navigation("Badges");

                    b.Navigation("Connections");

                    b.Navigation("Projects");

                    b.Navigation("ReviewsGiven");

                    b.Navigation("ReviewsReceived");
                });

            modelBuilder.Entity("Mactic.Api.Models.Community.Project", b =>
                {
                    b.Navigation("Dependencies");

                    b.Navigation("DependentProjects");

                    b.Navigation("Reviews");

                    b.Navigation("Usages");
                });
#pragma warning restore 612, 618
        }
    }
}
