using System.Text.Json.Serialization;

namespace Minimact.AspNetCore.Routing;

/// <summary>
/// Route manifest entry from transpiler
/// </summary>
public class RouteEntry
{
    [JsonPropertyName("route")]
    public string Route { get; set; } = "";

    [JsonPropertyName("componentPath")]
    public string ComponentPath { get; set; } = "";

    [JsonPropertyName("isPage")]
    public bool IsPage { get; set; }

    /// <summary>
    /// Derived component class name (e.g., "Index" from "Generated/pages/Index.cs")
    /// </summary>
    public string ComponentName { get; set; } = "";
}

/// <summary>
/// Route manifest generated by minimact transpiler
/// </summary>
public class RouteManifest
{
    public List<RouteEntry> Routes { get; set; } = new();
}
